### ISSUE TITLE
suggest managing history balance by pages

### ISSUE THREAD

**Issue by Honglei-Cong** [ontio/ontology-rosetta#38]
* manage history balance by pages
* define customized serialization functions for pages

for each account:
- "address + contract" : { current-page-num: n }

for each page:
- "address + contract + page_num" : { startBlockNum, endBlockNum, []{blocknum, balance}}

**Comment by xiemylogos** [comment]
optimize in :https://github.com/ontio/ontology-rosetta/pull/40
