### ISSUE TITLE
ONT Rosetta Setup Issue - "Failed to read data/server-config.json"

### ISSUE THREAD

**Issue by debasish22** [ontio/ontology-rosetta#95]
Hello ,

I was trying to set up ONT-Rosetta by following the set of instructions bur ran into issues. i am getting an error "Failed to read data/server-config.json". Please find the screenshot attached.
<img width="669" alt="ONT-Rosetta-NoeSetup" src="https://user-images.githubusercontent.com/30689502/124414929-4db9d780-dd71-11eb-8595-a226a5b6d52b.PNG">

**Comment by rongyi** [comment]
server-config.json is a file not dir
we run this command without error:
`docker run -v $(realpath Log):/data/Log -v $(realpath Chain):/data/Chain -v $(realpath server-config.json):/data/server-config.json ontology-rosetta`

**Comment by debasish22** [comment]
@rongyi could you please let me know if i am doing anything wrong as i have used the same docker run command as you have mentioned but i am running into issues

**Comment by rongyi** [comment]
The third volume map is mapping a file into docker, you're mapping a dir into docker, 
`$(realpath server-config.json):/data/server-config.json`, int outer file system, this is a regular json file, not dir

**Comment by debasish22** [comment]
@rongyi  Now i have created a file called server-config.json and then mapped into docker but still running into issues , can you please take a look.
![image](https://user-images.githubusercontent.com/30689502/124548978-208e2780-de4c-11eb-9655-968bb2e0cbf1.png)

**Comment by rongyi** [comment]
you can just map the server-config.json in this repo to docker, sorry I didn't describe it clearly.
